---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: <%= ENV['AWS_REGION'] || 'ap-northeast-1' %>
  availability_zone: <%= ENV['AWS_AZ'] || 'ap-northeast-1c' %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids: <%= ENV['AWS_SG_IDS'].split(",") %>
  associate_public_ip: true

transport:
  ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_SSH_KEY_ID']}") %>
  username: <%= ENV['AWS_EC2_USER'] || 'ec2-user' %>

provisioner:
  name: chef_zero
  cookbok_path: ["./cookbooks", "./site-cookbooks", "./test/cookboks"]

platforms:
  - name: amazon-2016.03.0
    driver:
      image_id: <%= ENV['AWS_EC2_AMI_ID'] || 'ami-f80e0596' %> # Tokyo
      instance_type: c4.2xlarge
    provisioner:
      chef_omnibus_install_options: " && sudo yum -y update"

suites:
  - name: default
    run_list:
      - build-essential
      - hhvm-rpm::prepare
      - hhvm-rpm::libdepends
      - hhvm-rpm::build_rpm
    attributes:
      hhvm_rpm:
        build:
          action: run
  - name: depends
    run_list:
      - build-essential
      - hhvm-rpm::prepare
      - hhvm-depends::build_glog
      - hhvm-depends::build_tbb
    attributes:
      glog:
        action: run
      tbb:
        action: run
  - name: packaged
    run_list:
      - test_rpm
    attributes:
