---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  cookbok_path: ["./cookbooks", "./site-cookbooks", "./test/cookboks"]

platforms:
  - name: amazonlinux201709
    driver:
      image: amazonlinux:2017.09-with-sources
      intermediate_instructions:
        # - RUN yum update -y
        # - RUN yum install sudo -y
        # - RUN useradd ec2-user
        # - RUN echo 'ec2-user ALL=NOPASSWD: ALL' > /etc/sudoers.d/ec2user

suites:
  - name: default
    run_list:
      - build-essential
      - hhvm-rpm::prepare
      - hhvm-rpm::libdepends
      - hhvm-rpm::build_rpm
    attributes:
      hhvm_rpm:
        build:
          action: run
  - name: depends
    run_list:
      - build-essential
      - hhvm-rpm::prepare
      - hhvm-depends::build_glog
      - hhvm-depends::build_tbb
    attributes:
      glog:
        action: run
      tbb:
        action: run
  - name: packaged
    run_list:
      - test_rpm
    attributes:
