#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'ark'
cookbook 'yum'
cookbook 'build-essential'

## Test
cookbook 'test_rpm', path: File.expand_path("../test/cookbooks/test_rpm", __FILE__)
